[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'htm']
on_i = 1

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_i = 1

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = 'unite.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_source = 'deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_source = 'neosnippet.vim'

[[plugins]]
repo = 'mattn/jscomplete-vim'
on_ft = ['javascript']
on_i = 1

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'tpope/vim-surround'
on_i = 1

[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html', 'htm']
on_i = 1

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
